### PR TITLE
Added invoice view

### LINKED ISSUE #44: Create Invoice history view
- [ ] Create a list where user can see old invoices 
- [ ] When pressing on the invoice user should be taken to the selected charging session.

### PR DESCRIPTION
**Pull request by LucasStrand**
Fixes #44
# Description
A user should be able to view their invoice history and what the invoice(s) consists of. However, depending on the users invoice status the view should show different information. One for where the user have not set up their invoice information, one fore where the user have but do not yet have any invoice, and lastly one for the user has set up their invoice and has invoices.

## Lists of changes

- [x] Added invoice view with corresponding relevant conditional statements to show the correct view
- [x] A viewmodel for the view with mock data.

image

image

image

## Testing

Keep in mind that the place view this view is supposed to be reached from is not yet accepted into dev. Therefore, to reach this view you are required to change an other button's navigation to this view!
- [ ] Change the variables `var isInvoiceSetUp: Bool = true` and `var isInvoiceEmpty: Bool = true` to true/false (of course you cannot set `isInvoiceSetUp` to false and `isInvoiced` to true. That wouldn't make any sense)

### CODE REVIEW

**Comment by LucasStrand** [comment]
oops goofed up an image

**Review by Yevve — APPROVED** [review]
A few weird names , hope they are just placeholders ...

**Comment by LucasStrand** [comment]
> A few weird names , hope they are just placeholders ...

Well, YOUR name is weird mr."Yevheniy Zanichkovskyy" 😤

**Review by scamdivine — CHANGES_REQUESTED** [review]
Great work needs some syntax fixes

**Pull request closed without merging**
