### PR TITLE
 Create pull_request_template.md

### LINKED ISSUE #23: Test pull request

### PR DESCRIPTION
**Pull request by LucasStrand**
I created a quick template to make writing pull requests easier in the future🙏🏻

fixes #23

### CODE REVIEW

**Review by scamdivine — APPROVED** [review]
great work

**Review by Yevve — CHANGES_REQUESTED** [review]
Change "closes " to fixes

**Review by filipfloden — APPROVED** [review]
Looks good!

**Review by Yevve — APPROVED** [review]
Very nice

**Pull request merged**
